<?php

if (!defined('XOOPS_ROOT_PATH')) exit();

require_once __DIR__.'/include/common.inc.php';

Xoonips_Utils::loadModinfoMessage('xoonips');

$modversion['name'] = _MI_XOONIPS_NAME;
$modversion['version'] = 4.20;
$modversion['description'] = _MI_XOONIPS_DESC;
$modversion['credits'] =
  'RIKEN, Japan (http://www.riken.jp/)';
$modversion['author'] =
  'The XooNIps Project (http://sourceforge.jp/projects/xoonips/)';
$modversion['help'] = 'help.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'module_icon.php';
$modversion['dirname'] = $myDirName;
$modversion['trust_dirname'] = 'xoonips';
$modversion['legacy_installer'] = array(
	'installer'   => array(
		'class' 	=> 'Installer',
		'namespace' => 'Xoonips',
		'filepath'	=> XOONIPS_TRUST_PATH . '/admin/class/installer/Installer.class.php'
	),
	'uninstaller' => array(
		'class' 	=> 'Uninstaller',
		'namespace' => 'Xoonips',
		'filepath'	=> XOONIPS_TRUST_PATH . '/admin/class/installer/Uninstaller.class.php'
	),
	'updater' => array(
		'class' 	=> 'Updater',
		'namespace' => 'Xoonips',
		'filepath'	=> XOONIPS_TRUST_PATH . '/admin/class/installer/Updater.class.php'
	)
);
$modversion['disable_legacy_2nd_installer'] = false;
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!

$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
$modversion['sqlfile']['mysql_alter'] = 'sql/mysql_alter.sql';
$modversion['tables'] = array(
	'{prefix}_{dirname}_item',
	'{prefix}_{dirname}_index_item_link',
	'{prefix}_{dirname}_index',
	'{prefix}_{dirname}_item_changelog',
	'{prefix}_{dirname}_item_type',
	'{prefix}_{dirname}_item_file',
	'{prefix}_{dirname}_config',
	'{prefix}_{dirname}_event_log',
	'{prefix}_{dirname}_oaipmh_item_status',
	'{prefix}_{dirname}_oaipmh_resumption_token',
	'{prefix}_{dirname}_item_related_to',
	'{prefix}_{dirname}_search_text',
	'{prefix}_{dirname}_item_title',
	'{prefix}_{dirname}_item_keyword',
	'{prefix}_{dirname}_data_type',
	'{prefix}_{dirname}_item_type_sort',
	'{prefix}_{dirname}_view_type',
	'{prefix}_{dirname}_view_data_relation',
	'{prefix}_{dirname}_default_item_field_group',
	'{prefix}_{dirname}_default_item_field_detail',
	'{prefix}_{dirname}_complement',
	'{prefix}_{dirname}_complement_detail',
	'{prefix}_{dirname}_item_field_value_set',
	'{prefix}_{dirname}_item_field_group',
	'{prefix}_{dirname}_item_field_detail',
	'{prefix}_{dirname}_item_field_detail_complement_link',
	'{prefix}_{dirname}_item_type_sort_detail',
	'{prefix}_{dirname}_item_users_link',
	'{prefix}_{dirname}_item_type_search_condition',
	'{prefix}_{dirname}_oaipmh_schema_item_type_link',
	'{prefix}_{dirname}_item_type_search_condition_detail',
	'{prefix}_{dirname}_oaipmh_schema_value_set',
	'{prefix}_{dirname}_oaipmh_schema',
	'{prefix}_{dirname}_oaipmh_schema_link',
	'{prefix}_{dirname}_item_type_field_group_link',
	'{prefix}_{dirname}_item_field_group_field_detail_link',
	'{prefix}_{dirname}_item_import_log',
	'{prefix}_{dirname}_item_import_link',
);

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'xoonips_search';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][] = array('name'=>_MI_XOONIPS_USER_REGISTER_ITEM,'url'=>'register.php');
$modversion['sub'][] = array('name'=>_MI_XOONIPS_USER_IMPORT_ITEM,'url'=>'itemimport.php');
$modversion['sub'][] = array('name'=>_MI_XOONIPS_USER_SEARCH,'url'=>'search.php?op=quick');
$modversion['sub'][] = array('name'=>_MI_XOONIPS_USER_EDIT_INDEX,'url'=>'editindex.php');

// Templates
$i = 1;
$modversion['templates'][$i]['file'] = 'breadcrumbs.inc.html';
$modversion['templates'][$i]['description'] = 'breadcrumbs navigation for each pages';
$i++;
$modversion['templates'][$i]['file'] = 'register.html';
$modversion['templates'][$i]['description'] = 'register item';
$i++;
$modversion['templates'][$i]['file'] = 'register_confirm.html';
$modversion['templates'][$i]['description'] = 'confirmation before register';
$i++;
$modversion['templates'][$i]['file'] = 'edit.html';
$modversion['templates'][$i]['description'] = 'edit item';
$i++;
$modversion['templates'][$i]['file'] = 'edit_confirm.html';
$modversion['templates'][$i]['description'] = 'confirm edit item';
$i++;
$modversion['templates'][$i]['file'] = 'detail.html';
$modversion['templates'][$i]['description'] = 'detail item';
$i++;
$modversion['templates'][$i]['file'] = 'delete_confirm.html';
$modversion['templates'][$i]['description'] = 'confirm delete item';
$i++;
$modversion['templates'][$i]['file'] = 'index_list.html';
$modversion['templates'][$i]['description'] = 'edit index page';
$i++;
$modversion['templates'][$i]['file'] = 'index.html';
$modversion['templates'][$i]['description'] = 'xoonips module top page';
$i++;
$modversion['templates'][$i]['file'] = 'itemtype_block.html';
$modversion['templates'][$i]['description'] = 'xoonips top page itemtype block';
$i++;
$modversion['templates'][$i]['file'] = 'detail_download_confirm.html';
$modversion['templates'][$i]['description'] = 'download confirmation';
$i++;
$modversion['templates'][$i]['file'] = 'list_index_block.html';
$modversion['templates'][$i]['description'] = 'index list block';
$i++;
$modversion['templates'][$i]['file'] = 'notifications.html';
$modversion['templates'][$i]['description'] = 'xoonips notifications';
$i++;
$modversion['templates'][$i]['file'] = 'tree.html';
$modversion['templates'][$i]['description'] = 'index tree';
$i++;
$modversion['templates'][$i]['file'] = 'list.html';
$modversion['templates'][$i]['description'] = 'item listing';
$i++;
$modversion['templates'][$i]['file'] = 'itemselect_item_list.html';
$modversion['templates'][$i]['description'] = 'item list of itemtypesearch';
$i++;
$modversion['templates'][$i]['file'] = 'advanced_search.html';
$modversion['templates'][$i]['description'] = 'advanced search result form';
$i++;
$modversion['templates'][$i]['file'] = 'index_edit.html';
$modversion['templates'][$i]['description'] = 'edit index sub';
$i++;
$modversion['templates'][$i]['file'] = 'index_description.html';
$modversion['templates'][$i]['description'] = 'index description';
$i++;
$modversion['templates'][$i]['file'] = 'header.html';
$modversion['templates'][$i]['description'] = 'main header';
$i++;
$modversion['templates'][$i]['file'] = 'footer.html';
$modversion['templates'][$i]['description'] = 'main footer';
$i++;
$modversion['templates'][$i]['file'] = 'register_select_itemtype.html';
$modversion['templates'][$i]['description'] = 'select itemtype to regist';
$i++;
$modversion['templates'][$i]['file'] = 'common_msg_sub.html';
$modversion['templates'][$i]['description'] = 'common message page in sub';
$i++;
$modversion['templates'][$i]['file'] = 'index_delete.html';
$modversion['templates'][$i]['description'] = 'delete index sub page';
$i++;
$modversion['templates'][$i]['file'] = 'index_move.html';
$modversion['templates'][$i]['description'] = 'move index sub page';
$i++;
$modversion['templates'][$i]['file'] = 'error.inc.html';
$modversion['templates'][$i]['description'] = 'xoonips error include';
$i++;
$modversion['templates'][$i]['file'] = 'print.inc.html';
$modversion['templates'][$i]['description'] = 'xoonips print include page';
$i++;
$modversion['templates'][$i]['file'] = 'itemowners_edit.html';
$modversion['templates'][$i]['description'] = 'edit item users page';
$i++;
$modversion['templates'][$i]['file'] = 'itemindex_confirm.html';
$modversion['templates'][$i]['description'] = 'item index edit confirm page';
$i++;
$modversion['templates'][$i]['file'] = 'search_tab.inc.html';
$modversion['templates'][$i]['description'] = 'search tab include page';
$i++;
$modversion['templates'][$i]['file'] = 'quicksearch.html';
$modversion['templates'][$i]['description'] = 'quick search page';
$i++;
$modversion['templates'][$i]['file'] = 'itemindex_edit.html';
$modversion['templates'][$i]['description'] = 'edit item index page';
$i++;
$modversion['templates'][$i]['file'] = 'register_top.html';
$modversion['templates'][$i]['description'] = 'item register';
$i++;
$modversion['templates'][$i]['file'] = 'upload_output.html';
$modversion['templates'][$i]['description'] = 'iframe for file upload output';
$i++;
$modversion['templates'][$i]['file'] = 'itemtype.html';
$modversion['templates'][$i]['description'] = 'view for itemtype';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_lastupdate.html';
$modversion['templates'][$i]['description'] = 'view for viewtype lastupdate';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_createuser.html';
$modversion['templates'][$i]['description'] = 'view for viewtype createuser';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_changelog.html';
$modversion['templates'][$i]['description'] = 'view for viewtype changelog';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_index.html';
$modversion['templates'][$i]['description'] = 'view for viewtype index';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_relatedTo.html';
$modversion['templates'][$i]['description'] = 'view for viewtype related item';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_date.html';
$modversion['templates'][$i]['description'] = 'view for viewtype date';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_preview.html';
$modversion['templates'][$i]['description'] = 'view for viewtype preview';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_fileupload.html';
$modversion['templates'][$i]['description'] = 'view for viewtype fileupload';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_downloadnotify.html';
$modversion['templates'][$i]['description'] = 'view for viewtype downloadnotify';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_readme.html';
$modversion['templates'][$i]['description'] = 'view for viewtype readme';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_rights.html';
$modversion['templates'][$i]['description'] = 'view for viewtype rights';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_url.html';
$modversion['templates'][$i]['description'] = 'view for viewtype url';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_pubmedId.html';
$modversion['templates'][$i]['description'] = 'view for viewtype pubmedId';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_isbn.html';
$modversion['templates'][$i]['description'] = 'view for viewtype isbn';
$i++;
$modversion['templates'][$i]['file'] = 'print.css';
$modversion['templates'][$i]['description'] = 'stylesheet for print';
$i++;
$modversion['templates'][$i]['file'] = 'style.css';
$modversion['templates'][$i]['description'] = 'stylesheet for screen';
$i++;
$modversion['templates'][$i]['file'] = 'itemimport.html';
$modversion['templates'][$i]['description'] = 'import item';
$i++;
$modversion['templates'][$i]['file'] = 'itemimport_tab.inc.html';
$modversion['templates'][$i]['description'] = 'import item tab';
$i++;
$modversion['templates'][$i]['file'] = 'itemimport_log.html';
$modversion['templates'][$i]['description'] = 'import item log';
$i++;
$modversion['templates'][$i]['file'] = 'itemimport_logdetail.html';
$modversion['templates'][$i]['description'] = 'import item log detail';
$i++;
$modversion['templates'][$i]['file'] = 'export_select.html';
$modversion['templates'][$i]['description'] = 'export select';

// removed libs/templates
$i++;
$modversion['templates'][$i]['file'] = 'error.html';
$modversion['templates'][$i]['description'] = 'error';
$i++;
$modversion['templates'][$i]['file'] = 'field.html';
$modversion['templates'][$i]['description'] = 'field';
$i++;
$modversion['templates'][$i]['file'] = 'field_group.html';
$modversion['templates'][$i]['description'] = 'field_group';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype.html';
$modversion['templates'][$i]['description'] = 'viewtype';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_checkbox.html';
$modversion['templates'][$i]['description'] = 'viewtype_checkbox';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_combobox.html';
$modversion['templates'][$i]['description'] = 'viewtype_combobox';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_date.html';
$modversion['templates'][$i]['description'] = 'viewtype_date';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_email.html';
$modversion['templates'][$i]['description'] = 'viewtype_email';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_groupname.html';
$modversion['templates'][$i]['description'] = 'viewtype_groupname';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_hidden.html';
$modversion['templates'][$i]['description'] = 'viewtype_hidden';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_kana.html';
$modversion['templates'][$i]['description'] = 'viewtype_kana';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_mbyte.html';
$modversion['templates'][$i]['description'] = 'viewtype_mbyte';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_password.html';
$modversion['templates'][$i]['description'] = 'viewtype_password';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_radiobox.html';
$modversion['templates'][$i]['description'] = 'viewtype_radiobox';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_text.html';
$modversion['templates'][$i]['description'] = 'viewtype_text';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_textarea.html';
$modversion['templates'][$i]['description'] = 'viewtype_textarea';
$i++;
$modversion['templates'][$i]['file'] = 'viewtype_timezone.html';
$modversion['templates'][$i]['description'] = 'viewtype_timezone';

// removed XooNIps Expand User Module
$i++;
$modversion['templates'][$i]['file'] = 'user_header.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_footer.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_breadcrumbs.inc.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_print.inc.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_print.css';
$modversion['templates'][$i]['description'] = 'stylesheet for print';
$i++;
$modversion['templates'][$i]['file'] = 'user_style.css';
$modversion['templates'][$i]['description'] = 'stylesheet for screen';
$i++;
$modversion['templates'][$i]['file'] = 'user_activate.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_delete.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_su.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_grouplist.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_groupinfo.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_groupregister.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_groupedit.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_groupmember.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_groupedit.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_groupmember.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_search.html';
$modversion['templates'][$i]['description'] = '';
$i++;
$modversion['templates'][$i]['file'] = 'user_list.html';
$modversion['templates'][$i]['description'] = '';
$i++;
// javascript
$modversion['templates'][$i]['file'] = 'library.js';
$modversion['templates'][$i]['description'] = 'javascript library';
$i++;
// ajax 
$modversion['templates'][$i]['file'] = 'ajax_userselect.html';
$modversion['templates'][$i]['description'] = 'user select ajax';
$i++;
$modversion['templates'][$i]['file'] = 'ajax_itemselect.html';
$modversion['templates'][$i]['description'] = 'item select ajax';
$i++;
$modversion['templates'][$i]['file'] = 'ajax_textfileinput.html';
$modversion['templates'][$i]['description'] = 'text file input ajax';
// popin library
$i++;
$modversion['templates'][$i]['file'] = 'popin.js';
$modversion['templates'][$i]['description'] = 'jquery popin library';
$i++;
$modversion['templates'][$i]['file'] = 'popin.css';
$modversion['templates'][$i]['description'] = 'stylesheet for jquery popin library';

// Blocks
$modversion['blocks'][1]['file'] = 'xoonips_blocks.php';
$modversion['blocks'][1]['name'] = _MI_XOONIPS_ITEM_BNAME1;
$modversion['blocks'][1]['description'] = 'Shows xoonips quick search block';
$modversion['blocks'][1]['show_func'] = 'b_xoonips_quick_search_show';
$modversion['blocks'][1]['edit_func'] = '';
$modversion['blocks'][1]['template'] = 'block_quicksearch.html';
$modversion['blocks'][1]['options'] = '';

$modversion['blocks'][2]['file'] = 'xoonips_blocks.php';
$modversion['blocks'][2]['name'] = _MI_XOONIPS_INDEX_BNAME1;
$modversion['blocks'][2]['description'] = 'browse block';
$modversion['blocks'][2]['show_func'] = 'b_xoonips_tree_show';
$modversion['blocks'][2]['edit_func'] = '';
$modversion['blocks'][2]['template'] = 'block_tree.html';
$modversion['blocks'][2]['options'] = '';

$modversion['blocks'][3]['file'] = 'xoonips_blocks.php';
$modversion['blocks'][3]['name'] = _MI_XOONIPS_ACCOUNT_BNAME1;
$modversion['blocks'][3]['description'] = 'Shows xoonips login block';
$modversion['blocks'][3]['show_func'] = 'b_xoonips_login_show';
$modversion['blocks'][3]['edit_func'] = '';
$modversion['blocks'][3]['template'] = 'block_login.html';
$modversion['blocks'][3]['options'] = '';

$modversion['blocks'][4]['file'] = 'xoonips_blocks.php';
$modversion['blocks'][4]['name'] = _MI_XOONIPS_ACCOUNT_BNAME2;
$modversion['blocks'][4]['description'] = 'Shows user menu';
$modversion['blocks'][4]['show_func'] = 'b_xoonips_user_show';
$modversion['blocks'][4]['template'] = 'block_usermenu.html';

$modversion['blocks'][5]['file'] = 'xoonips_blocks.php';
$modversion['blocks'][5]['name'] = _MI_XOONIPS_ITEMTYPE_BNAME1;
$modversion['blocks'][5]['description'] = 'Shows itemtypes';
$modversion['blocks'][5]['show_func'] = 'b_xoonips_itemtypes_show';
$modversion['blocks'][5]['template'] = 'block_itemtypes.html';
$modversion['blocks'][5]['can_clone'] = true;

// $modversion['onInstall'] = 'include/oninstall.inc.php';
// $modversion['onUpdate'] = 'include/onupdate.inc.php';
// $modversion['onUninstall'] = 'include/onuninstall.inc.php';

$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'xoonips_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'administrator';
$modversion['notification']['category'][1]['title'] = _MI_XOONIPS_ADMINISTRATOR_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_XOONIPS_ADMINISTRATOR_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array( 'notifications.php' );
$modversion['notification']['category'][1]['allow_bookmark'] = 0;

$modversion['notification']['category'][2]['name'] = 'user';
$modversion['notification']['category'][2]['title'] = _MI_XOONIPS_USER_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_XOONIPS_USER_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array( 'notifications.php');

$modversion['notification']['category'][3]['name'] = 'common';
$modversion['notification']['category'][3]['title'] = _MI_XOONIPS_COMMON_NOTIFY;
$modversion['notification']['category'][3]['description'] = _MI_XOONIPS_COMMON_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = array( 'notifications.php');

$modversion['notification']['event'][1]['name'] = 'account_certify';
$modversion['notification']['event'][1]['category'] = 'administrator';
$modversion['notification']['event'][1]['title'] = _MI_XOONIPS_ACCOUNT_CERTIFY_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_XOONIPS_ACCOUNT_CERTIFY_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_XOONIPS_ACCOUNT_CERTIFY_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = '';
$modversion['notification']['event'][1]['mail_subject'] = '';

$modversion['notification']['event'][2]['name'] = 'item_transfer';
$modversion['notification']['event'][2]['category'] = 'user';
$modversion['notification']['event'][2]['title'] = _MI_XOONIPS_USER_ITEM_TRANSFER_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_XOONIPS_USER_ITEM_TRANSFER_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_XOONIPS_USER_ITEM_TRANSFER_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = '';
$modversion['notification']['event'][2]['mail_subject'] = '';

$modversion['notification']['event'][3]['name'] = 'item_updated';
$modversion['notification']['event'][3]['category'] = 'user';
$modversion['notification']['event'][3]['title'] = _MI_XOONIPS_USER_ITEM_UPDATED_NOTIFY;
$modversion['notification']['event'][3]['caption'] = _MI_XOONIPS_USER_ITEM_UPDATED_NOTIFYCAP;
$modversion['notification']['event'][3]['description'] = _MI_XOONIPS_USER_ITEM_UPDATED_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = '';
$modversion['notification']['event'][3]['mail_subject'] = '';

$modversion['notification']['event'][4]['name'] = 'file_downloaded';
$modversion['notification']['event'][4]['category'] = 'user';
$modversion['notification']['event'][4]['title'] = _MI_XOONIPS_USER_FILE_DOWNLOADED_NOTIFY;
$modversion['notification']['event'][4]['caption'] = _MI_XOONIPS_USER_FILE_DOWNLOADED_NOTIFYCAP;
$modversion['notification']['event'][4]['description'] = _MI_XOONIPS_USER_FILE_DOWNLOADED_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = '';
$modversion['notification']['event'][4]['mail_subject'] = '';

$modversion['notification']['event'][5]['name'] = 'group';
$modversion['notification']['event'][5]['category'] = 'common';
$modversion['notification']['event'][5]['title'] = _MI_XOONIPS_COMMON_GROUP_NOTIFY;
$modversion['notification']['event'][5]['caption'] = _MI_XOONIPS_COMMON_GROUP_NOTIFYCAP;
$modversion['notification']['event'][5]['description'] = _MI_XOONIPS_COMMON_GROUP_NOTIFYDSC;
$modversion['notification']['event'][5]['mail_template'] = '';
$modversion['notification']['event'][]['mail_subject'] = '';

$modversion['notification']['event'][6]['name'] = 'item';
$modversion['notification']['event'][6]['category'] = 'common';
$modversion['notification']['event'][6]['title'] = _MI_XOONIPS_COMMON_ITEM_NOTIFY;
$modversion['notification']['event'][6]['caption'] = _MI_XOONIPS_COMMON_ITEM_NOTIFYCAP;
$modversion['notification']['event'][6]['description'] = _MI_XOONIPS_COMMON_ITEM_NOTIFYDSC;
$modversion['notification']['event'][6]['mail_template'] = '';
$modversion['notification']['event'][6]['mail_subject'] = '';

// Preference
$modversion['hidePreference'] = true;
